Front_Shop/src/java/models/Feedback.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package models;

/**
 *
 * @author DELL
 */
public class Feedback {

    private String name;
    private String gmail;
    private String proName;
    private String Feedback;
    private int RateStar;

    public Feedback() {
    }

    public Feedback(String name, String gmail, String proName, String Feedback, int RateStar) {
        this.name = name;
        this.gmail = gmail;
        this.proName = proName;
        this.Feedback = Feedback;
        this.RateStar = RateStar;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getGmail() {
        return gmail;
    }

    public void setGmail(String gmail) {
        this.gmail = gmail;
    }

    public String getProName() {
        return proName;
    }

    public void setProName(String proName) {
        this.proName = proName;
    }

    public String getFeedback() {
        return Feedback;
    }

    public void setFeedback(String Feedback) {
        this.Feedback = Feedback;
    }

    public int getRateStar() {
        return RateStar;
    }

    public void setRateStar(int RateStar) {
        this.RateStar = RateStar;
    }

  
}

Front_Shop/src/java/controller/account/AddUserServlet.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/JSP_Servlet/Servlet.java to edit this template
 */
package controller.account;

import dal.AccountDAO;
import helper.SendMail;
import java.io.IOException;
import java.io.PrintWriter;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import utlis.GetParam;

/**
 *
 * @author admin
 */
public class AddUserServlet extends HttpServlet {

    /**
     * Processes requests for both HTTP <code>GET</code> and <code>POST</code>
     * methods.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    protected boolean processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        String gmail = GetParam.getStringParam(request, "gmail", "Gmail",
                "^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$", "This is not gmail", 5, 50, null);
        String name = GetParam.getStringParam(request, "name", "Full Name",
                "^[a-zA-ZÀÁÂÃÈÉÊÌÍÒÓÔÕÙÚĂĐĨŨƠàáâãèéêìíòóôõùúăđĩũơƯĂẠẢẤẦẨẪẬẮẰẲẴẶẸẺẼỀỀỂẾưăạảấầẩẫậắằẳẵặẹẻẽềềểếỄỆỈỊỌỎỐỒỔỖỘỚỜỞỠỢỤỦỨỪễệỉịọỏốồổỗộớờởỡợụủứừỬỮỰỲỴÝỶỸửữựỳỵỷỹ\\s\\W|_]+$", "This is not name", 5, 50, null);
        if (gmail == null || name == null) {
            return false;
        }
        return true;
    }

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /**
     * Handles the HTTP <code>GET</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        request.setAttribute("mess", "");
        String gender = request.getParameter("gender");
        String role = request.getParameter("role");
        String gmail = request.getParameter("gmail");
        String name = request.getParameter("name");

        request.setAttribute("gender", gender);
        request.setAttribute("role", role);
        request.setAttribute("gmail", gmail);
        request.setAttribute("name", name);
        request.getRequestDispatcher("../view/AddUser.jsp").forward(request, response);
    }

    /**
     * Handles the HTTP <code>POST</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        if (processRequest(request, response)) {
            String gmail = request.getParameter("gmail");
            String name = request.getParameter("name");
            String gender = request.getParameter("gender");
            String roleid = request.getParameter("role");
String role="";
            AccountDAO acc = new AccountDAO();
            acc.AddAccount(gmail, name, gender, roleid);
            request.setAttribute("mess", "Add Sucessfull");
            if (roleid.equals("2")) {
                role = "Maketing";
            }
            if (roleid.equals("3")) {
                role = "Sale";
            }

            SendMail send = new SendMail();
            send.SendGmail(gmail, "Create Account", "Welcom to Front Shop! We have created an account for you as role is " + role + " with gmail: " + gmail + " and password: 123456789a ");
            request.setAttribute("gender", gender);
            request.setAttribute("role", roleid);
            request.setAttribute("gmail", gmail);
            request.setAttribute("name", name);
            request.getRequestDispatcher("../view/AddUser.jsp").forward(request, response);
        } else {

            this.doGet(request, response);
        }
    }

    /**
     * Returns a short description of the servlet.
     *
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}

Front_Shop/src/java/controller/account/ChangePasswordServlet.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/JSP_Servlet/Servlet.java to edit this template
 */
package controller.account;

import dal.AccountDAO;
import java.io.IOException;
import java.io.PrintWriter;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.servlet.http.HttpSession;
import models.Account;
import utlis.GetParam;

/**
 *
 * @author admin
 */
public class ChangePasswordServlet extends HttpServlet {

    /**
     * Processes requests for both HTTP <code>GET</code> and <code>POST</code>
     * methods.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    protected boolean processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        HttpSession session = request.getSession();
        Account acc = (Account) session.getAttribute("account");

        String oldPass = request.getParameter("oldpass");
        if(acc.getPassword().equals(oldPass)){
            return true;
        }
        else{
            return false;
        }
    }

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /**
     * Handles the HTTP <code>GET</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        String oldPass = request.getParameter("oldpass");
        String newPass = request.getParameter("newpass");
        String rePass = request.getParameter("repass");
        //request.setAttribute("oldpass", oldPass);
        //request.setAttribute("newpass", newPass);
        //request.setAttribute("repass", rePass);
        request.getRequestDispatcher("../view/ChangePassword.jsp").forward(request, response);
    }

    /**
     * Handles the HTTP <code>POST</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        HttpSession session = request.getSession();
        Account acc = (Account) session.getAttribute("account");
        AccountDAO dao = new AccountDAO();
        if (!processRequest(request, response)) {
            request.setAttribute("mess", "Wrong old Password");
            this.doGet(request, response);
        }
        
        String newPass = GetParam.getStringParam(request, "newpass", "New Password",
                "^(?=.*[A-Za-z])(?=.*\\d)[A-Za-z\\d]{8,}$", "Minimum eight characters, at least one letter and one number", 8, 50, null);
        if(newPass == null){
            //request.setAttribute("mess", "Wrong New Password");
            this.doGet(request, response);
        }
        
        String rePass = request.getParameter("repass");
        
        if(newPass.equals(rePass)){
            dao.changePassword(acc.getGmail(), newPass);
            request.setAttribute("mess", "Change Password Successful");
            request.getRequestDispatcher("../view/ChangePassword.jsp").forward(request, response);
        }
        else{
            request.setAttribute("mess", "New Password not equal Re Password");
            this.doGet(request, response);
        }
        
    }

    /**
     * Returns a short description of the servlet.
     *
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}

Front_Shop/src/java/controller/account/ForgotPasswordServlet.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/JSP_Servlet/Servlet.java to edit this template
 */
package controller.account;

import dal.AccountDAO;
import helper.GetRandom;
import helper.SendMail;
import java.io.IOException;
import java.io.PrintWriter;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.servlet.http.HttpSession;
import models.Account;
import utlis.GetParam;

/**
 *
 * @author dinhd513
 */
public class ForgotPasswordServlet extends HttpServlet {

    /**
     * Processes requests for both HTTP <code>GET</code> and <code>POST</code>
     * methods.
     *
     * @param request servlet request
     * @param response servlet response
     * @return
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    protected boolean processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");

        String gmail = GetParam.getStringParam(request, "gmailToForgot", "Gmail",
                "^[\\w-\\.]+@([\\w-]+\\.)+[\\w-]{2,4}$", "This is not gmail", 5, 50, null);

        AccountDAO dao = new AccountDAO();
        Account acc = dao.searchAccByID(gmail);
        if (acc != null && gmail != null) {
            HttpSession session = request.getSession();
            session.setAttribute("gmailToForgot", gmail);
           session.setAttribute("Check", "false");
            GetRandom getRandom = new GetRandom();
            String code = getRandom.generateRandomNumber(5);
            session.setAttribute("codeToVerify", code); 
            session.setMaxInactiveInterval(200);
            String subject = "Verification Email";
            String text = "Hello\n"
                    + "\n"
                    + "You have just requested a password reset for your account on the Front page.\n"
                    + "Below is the verification code that the requester is you\n " + code + "\n"
                    + "\n"
                    + "\n"
                    + "Kind Regards, Front";
            SendMail send = new SendMail();
            send.SendGmail(gmail, subject, text);
            return true;
        }
        return false;

    }

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /**
     * Handles the HTTP <code>GET</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        request.setAttribute("mess", "Your gmail is not esist");
        request.getRequestDispatcher("../view/ForgotPassword.jsp").forward(request, response);
    }

    /**
     * Handles the HTTP <code>POST</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        if (processRequest(request, response) == true) {


            request.setAttribute("mess", "Verification code has been sent to your email");
            request.setAttribute("inputCode", "block");
            request.setAttribute("inputGmail", "none");
            request.setAttribute("inputNewPassword", "none");
            request.getRequestDispatcher("../view/ForgotPassword.jsp").forward(request, response);
        }
        this.doGet(request, response);
    }

    /**
     * Returns a short description of the servlet.
     *
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}

Front_Shop/src/java/controller/account/ProfileServlet.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/JSP_Servlet/Servlet.java to edit this template
 */
package controller.account;

import dal.AccountDAO;
import java.io.IOException;
import java.io.PrintWriter;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.servlet.http.HttpSession;
import java.util.ArrayList;
import java.util.List;
import models.Account;
import models.Address;

/**
 *
 * @author admin
 */
public class ProfileServlet extends HttpServlet {

    /**
     * Processes requests for both HTTP <code>GET</code> and <code>POST</code>
     * methods.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
       
    }

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /**
     * Handles the HTTP <code>GET</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
         AccountDAO dao = new AccountDAO();
        HttpSession session = request.getSession();
        Account acc = (Account) session.getAttribute("account");
        List<Address> list = dao.getAllAddress(acc.getGmail());

        request.setAttribute("listadd", list);
        request.getRequestDispatcher("../view/Profile.jsp").forward(request, response);
    }

    /**
     * Handles the HTTP <code>POST</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    /**
     * Returns a short description of the servlet.
     *
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}

Front_Shop/web/view/FeedbackList.jsp
<%-- 
    Document   : PostManage
    Created on : Jun 6, 2023, 10:38:06 AM
    Author     : DELL
--%>

<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <!-- Boxicons -->
        <link href='https://unpkg.com/boxicons@2.0.9/css/boxicons.min.css' rel='stylesheet'>
        <!-- My CSS -->
        <link rel="stylesheet" href="../stylesheet/feedbackList.css">

        <title>Feedback List</title>
    </head>
    <body>
        <!-- SIDEBAR -->
        <jsp:include page="../components/MenuBar_Manage.jsp">
            <jsp:param name="activeFeedback" value="active"/>
            <jsp:param name="hrefFeedback" value="../view/feedback"/>
            <jsp:param name="hrefMarketing" value="../view/marketingDashboard?table=product"/>
        </jsp:include>
        <!-- SIDEBAR -->

        <!-- CONTENT -->
        <section id="content">
            <!-- NAVBAR -->
            <nav>
                <i class='bx bx-menu' ></i>
                <a href="#" class="nav-link">Categories</a>

                <input type="checkbox" id="switch-mode" hidden>


            </nav>
            <!-- NAVBAR -->
            <!-- MAIN -->
            <main>

                <div class="head-title">
                    <div class="left">
                        <a href="../view/feedback"><h1>Feedback List</h1></a>
                    </div>
                </div>





                <div class="table-data">
                    <div class="order">
                        <div class="head">
                            <h3>Recent feedback</h3>
                            <form class="form" action="../view/searchFeedback" method="post">
                                <button>
                                    <svg width="17" height="16" fill="none" xmlns="http://www.w3.org/2000/svg" role="img" aria-labelledby="search">
                                    <path d="M7.667 12.667A5.333 5.333 0 107.667 2a5.333 5.333 0 000 10.667zM14.334 14l-2.9-2.9" stroke="currentColor" stroke-width="1.333" stroke-linecap="round" stroke-linejoin="round"></path>
                                    </svg>
                                </button>
                                <input class="input" placeholder="Type your text" required="" type="text" name="txt">
                                <button class="reset" type="reset">
                                    <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                                    <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12"></path>
                                    </svg>
                                </button>
                            </form>


                            <style>
                                #rate-select {
                                    padding: 8px;
                                    font-size: 16px;
                                    border: 1px solid #ccc;
                                    border-radius: 20px;
                                    width: 200px;
                                    color: #888; /* Màu chữ mờ */
                                }

                                #rate-select option {
                                    padding: 8px;
                                }

                                #rate-select option:first-child {
                                    color: #000; /* Màu chữ bình thường */
                                }
                            </style>

                            <select id="rate-select" onchange="redirectToSelectedUrl()">
                                <option value="">Filter by Star</option>
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                                <option value="5">5</option>
                            </select>

                            <script>
                                function redirectToSelectedUrl() {
                                    var selectElement = document.getElementById("rate-select");
                                    var selectedOption = selectElement.options[selectElement.selectedIndex];
                                    var selectedValue = selectedOption.value;
                                    var selectedUrl = "../view/filterRate?frate=" + selectedValue;

                                    window.location.href = selectedUrl; // Chuyển hướng đến đường dẫn đã chọn
                                }
                            </script>





                        </div>
                        <table  style="width: 100%;">
                            <thead>
                                <tr>
                                    <th  style="width: 15%;">Name</th>
                                    <th style="width: 20%;">Gmail</th>
                                    <th style="width: 20%;">Product Name</th>
                                    <th style="width: 30%;">Feedback</th>
                                    <th style="width: 15%; padding-left: 60px">RateStar</th>




                                </tr>
                            </thead>
                            <c:forEach items="${listF}" var="f">


                                <tr>
                                <style>
                                    a{
                                        color: black;
                                    }
                                </style>
                                    <td style="margin-top: 30px"><a href="../view/feedbackDetail?pName=${f.proName}">${f.name}</a></td>
                                    <td><a href="../view/feedbackDetail?pName=${f.proName}">${f.gmail}</a></td>
                                    <td><a href="../view/feedbackDetail?pName=${f.proName}">${f.proName}</a></td>
                                    <td><a href="../view/feedbackDetail?pName=${f.proName}">${f.feedback}</a></td>
                                    <td>
                                        <c:if test="${f.rateStar == 1}">
                                            <div class="rating" style="width: 150px">
                                                <input type="radio" id="star1" name="rate" value="1">
                                                <label style="color: orange;"for="star1" title="text"></label></div>
                                            </c:if>
                                            <c:if test="${f.rateStar == 2}">
                                            <div class="rating" style="width: 150px">
                                                <input type="radio" id="star1" name="rate" value="1">
                                                <label style="color: orange;"for="star1" title="text"></label>
                                                <input type="radio" id="star2" name="rate" value="2">
                                                <label style="color: orange;"for="star2" title="text"></label></div>
                                            </c:if>

                                        <c:if test="${f.rateStar == 3}">
                                            <div class="rating" style="width: 150px">
                                                <input type="radio" id="star1" name="rate" value="1">
                                                <label style="color: orange;"for="star1" title="text"></label>
                                                <input type="radio" id="star2" name="rate" value="2">
                                                <label style="color: orange;"for="star2" title="text"></label>
                                                <input  type="radio" id="star3" name="rate" value="3">
                                                <label style="color: orange;"for="star3" title="text"></label></div>
                                            </c:if>
                                            <c:if test="${f.rateStar == 4}">
                                            <div class="rating" style="width: 150px">
                                                <input type="radio" id="star1" name="rate" value="1">
                                                <label style="color: orange;"for="star1" title="text"></label>
                                                <input type="radio" id="star2" name="rate" value="2">
                                                <label style="color: orange;"for="star2" title="text"></label>
                                                <input  type="radio" id="star3" name="rate" value="3">
                                                <label style="color: orange;"for="star3" title="text"></label>
                                                <input type="radio" id="star4" name="rate" value="4">
                                                <label style="color: orange;"for="star4" title="text"></label></div>
                                            </c:if>
                                            <c:if test="${f.rateStar == 5}">
                                            <div class="rating" style="width: 150px">
                                                <input  type="radio" id="star1" name="rate" value="1">
                                                <label style="color: orange;" for="star1" title="text"></label>
                                                <input type="radio" id="star2" name="rate" value="2">
                                                <label style="color: orange;" for="star2" title="text"></label>
                                                <input  type="radio" id="star3" name="rate" value="3">
                                                <label style="color: orange;" for="star3" title="text"></label>
                                                <input type="radio" id="star4" name="rate" value="4">
                                                <label  style="color: orange;"for="star4" title="text"></label>
                                                <input type="radio" id="star5" name="rate" value="5">
                                                <label style="color: orange;"for="star5" title="text"></label></div>
                                            </c:if> 

                                    </td>
                                
                                </tr>

                            </c:forEach>
                        </table>
                    </div>


            </main>
            <div class="pagination" style="margin-right: 200px; float: right;">
                <style>
                    .active{
                        background-color: black;
                        color: white;
                    }
                </style>
                <c:forEach begin="1" end="${endPage}" var="e">
                    <a  class="${requestScope.index == e? "active" : ""}" href="../view/feedback?index=${e}">${e}</a> 
                </c:forEach>
            </div>

            <!-- MAIN -->
        </section>

        <!-- CONTENT -->
        <script src="../js/MaketingPage.js"></script>
    </body>




</html>